apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.14.2
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false" # Disable security features
            - name: xpack.security.transport.ssl.enabled
              value: "false" # Disable SSL for transport layer
            - name: ES_JAVA_OPTS
              value: "-Xms2g -Xmx2g" # Set heap size to 2 GB
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
          resources:
            requests:
              memory: "4Gi"  # Increase memory request
              cpu: "1"
            limits:
              memory: "4Gi"  # Increase memory limit
              cpu: "1"
      volumes:
        - name: elasticsearch-data
          emptyDir: {}


---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  type: LoadBalancer
