apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopify-app
  labels:
    app: shopify
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopify
  template:
    metadata:
      labels:
        app: shopify
    spec:
      containers:
        - name: shopify-app
          image: binod6119/fenix:v7
          ports:
            - containerPort: 8085
          env:
            - name: ELASTICSEARCH_HOST
              value: "elasticsearch:9200"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 30
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: shopify-app
spec:
  selector:
    app: shopify
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer
